### ISSUE TITLE
meta: open-sourcing

### ISSUE THREAD

**Issue by ggreif** [dfinity/threshold#20]
Decider: https://dfinity.atlassian.net/browse/IC-1464

Before flipping the switch
- [x] check license
- [x] CI (see #17)
- [x] finalise IDL (see #15)
- [ ] close as many issues as possible
- [x] require contributor agreements? — this is likely automatic

After flipping the switch
- [x] https://github.com/dfinity/repositories-open-to-contributions/pull/25

**Comment by ggreif** [comment]
This is done now.
